# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 03:51
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('LeaseDetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='lease',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
