# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-15 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
